spring:
  profiles:
    active: dev
server:
  port: 8761
eureka:
  server:
    evictionIntervalTimerInMs: 5000
    enable-self-preservation: false
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true