spring:
  application:
    name: flatterer-center

eureka:
    client:
        registerWithEureka: true  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        registryFetchIntervalSeconds: 5
        serviceUrl:
          defaultZone: http://192.168.26.27:8761/eureka/,http://192.168.26.28:8761/eureka/,http://192.168.26.29:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true #启用shutdown端点
      sensitive: false
logging:
  level:
    com.stone.flatterservice: DEBUG